-- ==============================================================================
-- ELEVEN NATION — SAFE INCREMENTAL / DELTA SUPABASE MIGRATION
-- 100% Idempotent: Uses IF NOT EXISTS, DROP POLICY IF EXISTS, and SAFE ALTERs
-- ==============================================================================

-- Enable UUID extension if not enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ------------------------------------------------------------------------------
-- 1. PROFILES TABLE & AUTH TRIGGER
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  phone TEXT,
  avatar_url TEXT,
  default_district TEXT DEFAULT 'Dhaka',
  default_city TEXT,
  default_address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Trigger function to automatically create a profile when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, phone, default_district, default_city, default_address, created_at, updated_at)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', SPLIT_PART(NEW.email, '@', 1)),
    COALESCE(NEW.raw_user_meta_data->>'phone', ''),
    COALESCE(NEW.raw_user_meta_data->>'default_district', 'Dhaka'),
    COALESCE(NEW.raw_user_meta_data->>'default_city', ''),
    COALESCE(NEW.raw_user_meta_data->>'default_address', ''),
    NOW(),
    NOW()
  )
  ON CONFLICT (id) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    phone = EXCLUDED.phone,
    updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ------------------------------------------------------------------------------
-- 2. CATEGORIES TABLE
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.categories (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public.categories (id, name, slug)
VALUES
  ('cat-player-edition', 'Player Edition', 'player-edition'),
  ('cat-fan-edition', 'Fan Edition', 'fan-edition'),
  ('cat-retro', 'Retro', 'retro'),
  ('cat-special-edition', 'Special Edition', 'special-edition'),
  ('cat-world-cup', 'World Cup', 'world-cup')
ON CONFLICT (id) DO NOTHING;

-- ------------------------------------------------------------------------------
-- 3. PRODUCTS SCHEMA SAFETY (Add missing columns if not present)
-- ------------------------------------------------------------------------------
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS category_id TEXT REFERENCES public.categories(id) ON DELETE SET NULL;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS fabric_details TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS fit_type TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS compare_at_price NUMERIC;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS rating NUMERIC DEFAULT 5.0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS review_count INTEGER DEFAULT 0;

-- ------------------------------------------------------------------------------
-- 4. PRODUCT PLAYERS TABLE (Many-to-Many with Customization Fee)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.product_players (
  product_id TEXT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  player_id TEXT NOT NULL REFERENCES public.players(id) ON DELETE CASCADE,
  additional_price NUMERIC DEFAULT 0,
  PRIMARY KEY (product_id, player_id)
);

-- ------------------------------------------------------------------------------
-- 5. PRODUCT INVENTORY TABLE (Relational Stock Management)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.product_inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id TEXT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  size TEXT NOT NULL,
  stock INTEGER NOT NULL DEFAULT 0,
  sku TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_product_size UNIQUE (product_id, size)
);

-- ------------------------------------------------------------------------------
-- 6. PRODUCT IMAGES TABLE (Multi-Angle Gallery)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.product_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id TEXT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  image_type TEXT DEFAULT 'front',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 7. CART ITEMS TABLE (Persistent Customer Bag)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cart_items (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id TEXT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  size TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  player_name TEXT,
  player_number TEXT,
  is_custom BOOLEAN DEFAULT FALSE,
  customization_fee NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 8. WISHLIST TABLE (Persistent Saved Items)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.wishlist (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id TEXT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_user_wishlist_product UNIQUE (user_id, product_id)
);

-- ------------------------------------------------------------------------------
-- 9. ORDERS & ORDER ITEMS COLUMN SAFETY
-- ------------------------------------------------------------------------------
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS timeline JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS courier_name TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS courier_tracking_number TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS delivery_location TEXT DEFAULT 'dhaka';
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS district TEXT DEFAULT 'Dhaka';
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS city_area TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS customization_total NUMERIC DEFAULT 0;

ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS customization_fee NUMERIC DEFAULT 0;
ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS is_custom BOOLEAN DEFAULT FALSE;
ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS player_name TEXT;
ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS player_number TEXT;

-- ------------------------------------------------------------------------------
-- 10. REVIEWS COLUMN SAFETY
-- ------------------------------------------------------------------------------
ALTER TABLE public.reviews ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.reviews ADD COLUMN IF NOT EXISTS verified_purchase BOOLEAN DEFAULT FALSE;
ALTER TABLE public.reviews ADD COLUMN IF NOT EXISTS player_edition_bought TEXT;
ALTER TABLE public.reviews ADD COLUMN IF NOT EXISTS approved BOOLEAN DEFAULT TRUE;

-- ------------------------------------------------------------------------------
-- 11. INDEXES (Fast Queries & Foreign Key Lookups)
-- ------------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_products_slug ON public.products(slug);
CREATE INDEX IF NOT EXISTS idx_products_club_id ON public.products(club_id);
CREATE INDEX IF NOT EXISTS idx_products_category_id ON public.products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_active ON public.products(active);
CREATE INDEX IF NOT EXISTS idx_product_inventory_product_id ON public.product_inventory(product_id);
CREATE INDEX IF NOT EXISTS idx_product_inventory_sku ON public.product_inventory(sku);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON public.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_order_number ON public.orders(order_number);
CREATE INDEX IF NOT EXISTS idx_orders_customer_phone ON public.orders(customer_phone);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON public.order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product_id ON public.order_items(product_id);
CREATE INDEX IF NOT EXISTS idx_cart_items_user_id ON public.cart_items(user_id);
CREATE INDEX IF NOT EXISTS idx_wishlist_user_id ON public.wishlist(user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_product_id ON public.reviews(product_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON public.reviews(user_id);

-- ------------------------------------------------------------------------------
-- 12. ROW LEVEL SECURITY (RLS) & IDEMPOTENT POLICIES
-- ------------------------------------------------------------------------------

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clubs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wishlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
DROP POLICY IF EXISTS "Users can view their own profile" ON public.profiles;
CREATE POLICY "Users can view their own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Public Catalog Policies
DROP POLICY IF EXISTS "Public read on categories" ON public.categories;
CREATE POLICY "Public read on categories" ON public.categories FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public read on clubs" ON public.clubs;
DROP POLICY IF EXISTS "Allow public read on active clubs" ON public.clubs;
CREATE POLICY "Public read on clubs" ON public.clubs FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public read on players" ON public.players;
DROP POLICY IF EXISTS "Allow public read on players" ON public.players;
CREATE POLICY "Public read on players" ON public.players FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public read on active products" ON public.products;
DROP POLICY IF EXISTS "Allow public read on active products" ON public.products;
CREATE POLICY "Public read on active products" ON public.products FOR SELECT USING (active = true);

DROP POLICY IF EXISTS "Public read on product players" ON public.product_players;
CREATE POLICY "Public read on product players" ON public.product_players FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public read on product inventory" ON public.product_inventory;
CREATE POLICY "Public read on product inventory" ON public.product_inventory FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public read on product images" ON public.product_images;
CREATE POLICY "Public read on product images" ON public.product_images FOR SELECT USING (true);

-- Cart Items Policies (Strict User Isolation)
DROP POLICY IF EXISTS "Users can view their own cart items" ON public.cart_items;
CREATE POLICY "Users can view their own cart items" ON public.cart_items FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert into their own cart" ON public.cart_items;
CREATE POLICY "Users can insert into their own cart" ON public.cart_items FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own cart items" ON public.cart_items;
CREATE POLICY "Users can update their own cart items" ON public.cart_items FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own cart items" ON public.cart_items;
CREATE POLICY "Users can delete their own cart items" ON public.cart_items FOR DELETE USING (auth.uid() = user_id);

-- Wishlist Policies (Strict User Isolation)
DROP POLICY IF EXISTS "Users can view their own wishlist" ON public.wishlist;
CREATE POLICY "Users can view their own wishlist" ON public.wishlist FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert into their own wishlist" ON public.wishlist;
CREATE POLICY "Users can insert into their own wishlist" ON public.wishlist FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete from their own wishlist" ON public.wishlist;
CREATE POLICY "Users can delete from their own wishlist" ON public.wishlist FOR DELETE USING (auth.uid() = user_id);

-- Reviews Policies
DROP POLICY IF EXISTS "Public read on approved reviews" ON public.reviews;
DROP POLICY IF EXISTS "Allow public read on approved reviews" ON public.reviews;
CREATE POLICY "Public read on approved reviews" ON public.reviews FOR SELECT USING (approved = true);

DROP POLICY IF EXISTS "Allow anyone to insert reviews" ON public.reviews;
DROP POLICY IF EXISTS "Authenticated users can insert reviews" ON public.reviews;
CREATE POLICY "Authenticated users can insert reviews" ON public.reviews FOR INSERT WITH CHECK (auth.uid() IS NOT NULL AND (user_id IS NULL OR user_id = auth.uid()));

DROP POLICY IF EXISTS "Users can update their own reviews" ON public.reviews;
CREATE POLICY "Users can update their own reviews" ON public.reviews FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own reviews" ON public.reviews;
CREATE POLICY "Users can delete their own reviews" ON public.reviews FOR DELETE USING (auth.uid() = user_id);

-- Orders Policies
DROP POLICY IF EXISTS "Allow anyone to insert orders" ON public.orders;
DROP POLICY IF EXISTS "Allow read orders by ID or user" ON public.orders;
DROP POLICY IF EXISTS "Users can view their own orders" ON public.orders;
CREATE POLICY "Users can view their own orders" ON public.orders FOR SELECT USING (
  (auth.uid() IS NOT NULL AND user_id = auth.uid()) OR (user_id IS NULL)
);

CREATE POLICY "Anyone can create orders" ON public.orders FOR INSERT WITH CHECK (
  user_id IS NULL OR user_id = auth.uid()
);

-- Order Items Policies
DROP POLICY IF EXISTS "Allow anyone to insert order items" ON public.order_items;
DROP POLICY IF EXISTS "Allow read order items" ON public.order_items;
DROP POLICY IF EXISTS "Users can view order items of their accessible orders" ON public.order_items;
CREATE POLICY "Users can view order items of their accessible orders" ON public.order_items FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.orders
    WHERE orders.id = order_items.order_id
    AND (orders.user_id = auth.uid() OR orders.user_id IS NULL)
  )
);

CREATE POLICY "Anyone can insert order items" ON public.order_items FOR INSERT WITH CHECK (true);

-- ------------------------------------------------------------------------------
-- 13. ORDER IDEMPOTENCY KEYS (Deduplication & Concurrency Protection)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.order_idempotency_keys (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  idempotency_key TEXT NOT NULL UNIQUE,
  order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '24 hours')
);

CREATE INDEX IF NOT EXISTS idx_order_idempotency_keys_key ON public.order_idempotency_keys(idempotency_key);
CREATE INDEX IF NOT EXISTS idx_order_idempotency_keys_created_at ON public.order_idempotency_keys(created_at);

ALTER TABLE public.order_idempotency_keys ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Service role can manage idempotency keys" ON public.order_idempotency_keys;
CREATE POLICY "Service role can manage idempotency keys" ON public.order_idempotency_keys FOR ALL USING (true);

-- ------------------------------------------------------------------------------
-- 14. ATOMIC ORDER CREATION & INVENTORY DEDUCTION (Row Locking RPC)
-- ------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.create_order_atomic(
  order_payload JSONB,
  items_payload JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $
DECLARE
  v_order_id UUID;
  v_order_number TEXT;
  v_item JSONB;
  v_product_id UUID;
  v_requested_qty INTEGER;
  v_requested_size TEXT;
  v_curr_stock INTEGER;
  v_curr_sizes JSONB;
  v_new_sizes JSONB;
  v_size_found BOOLEAN;
  v_size_elem JSONB;
  v_avail_size_stock INTEGER;
  v_new_size_stock INTEGER;
  v_product_name TEXT;
  v_product_selling_price NUMERIC;
  v_product_cost_price NUMERIC;
BEGIN
  -- 1. Basic validation
  IF items_payload IS NULL OR jsonb_array_length(items_payload) = 0 THEN
    RAISE EXCEPTION 'Order creation failed: at least one order item is required.';
  END IF;

  v_order_number := order_payload->>'order_number';
  IF v_order_number IS NULL OR trim(v_order_number) = '' THEN
    RAISE EXCEPTION 'Order number is required';
  END IF;

  -- 2. Lock each product row FOR UPDATE and validate stock
  FOR v_item IN SELECT * FROM jsonb_array_elements(items_payload) LOOP
    v_product_id := (v_item->>'product_id')::UUID;
    v_requested_size := v_item->>'size';
    v_requested_qty := (v_item->>'quantity')::INTEGER;

    IF v_requested_qty <= 0 THEN
      RAISE EXCEPTION 'Invalid item quantity: %', v_requested_qty;
    END IF;

    -- Row-level locking on products table
    SELECT name, stock, sizes, selling_price, cost_price
    INTO v_product_name, v_curr_stock, v_curr_sizes, v_product_selling_price, v_product_cost_price
    FROM public.products
    WHERE id = v_product_id AND status = 'active'
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Product % is not found or inactive', v_product_id;
    END IF;

    IF v_curr_stock < v_requested_qty THEN
      RAISE EXCEPTION 'Insufficient inventory for %: requested %, but only % in stock',
        v_product_name, v_requested_qty, v_curr_stock;
    END IF;

    -- Validate and deduct specific size variant
    v_size_found := false;
    v_new_sizes := '[]'::jsonb;

    FOR v_size_elem IN SELECT * FROM jsonb_array_elements(v_curr_sizes) LOOP
      IF lower(v_size_elem->>'size') = lower(v_requested_size) THEN
        v_size_found := true;
        v_avail_size_stock := (v_size_elem->>'stock')::INTEGER;

        IF v_avail_size_stock < v_requested_qty THEN
          RAISE EXCEPTION 'Insufficient stock for % (Size %): requested %, available %',
            v_product_name, v_requested_size, v_requested_qty, v_avail_size_stock;
        END IF;

        v_new_size_stock := v_avail_size_stock - v_requested_qty;
        v_new_sizes := v_new_sizes || jsonb_build_object('size', v_size_elem->>'size', 'stock', v_new_size_stock);
      ELSE
        v_new_sizes := v_new_sizes || v_size_elem;
      END IF;
    END LOOP;

    IF NOT v_size_found THEN
      RAISE EXCEPTION 'Size % not found for product %', v_requested_size, v_product_name;
    END IF;

    -- Update inventory atomically
    UPDATE public.products
    SET
      sizes = v_new_sizes,
      stock = stock - v_requested_qty,
      updated_at = NOW()
    WHERE id = v_product_id;
  END LOOP;

  -- 3. Insert Order
  INSERT INTO public.orders (
    order_number,
    customer_id,
    customer_name,
    customer_email,
    customer_phone,
    shipping_address,
    city,
    postal_code,
    items_count,
    subtotal,
    customization_total,
    delivery_fee,
    discount,
    total_amount,
    total_cost,
    gross_profit,
    profit_margin_percent,
    payment_method,
    payment_status,
    order_status,
    courier_name,
    tracking_number,
    admin_notes,
    customer_notes,
    is_custom_order
  ) VALUES (
    v_order_number,
    NULLIF(order_payload->>'customer_id', '')::UUID,
    order_payload->>'customer_name',
    order_payload->>'customer_email',
    order_payload->>'customer_phone',
    order_payload->>'shipping_address',
    COALESCE(order_payload->>'city', 'Dhaka'),
    order_payload->>'postal_code',
    (order_payload->>'items_count')::INTEGER,
    (order_payload->>'subtotal')::NUMERIC,
    COALESCE((order_payload->>'customization_total')::NUMERIC, 0),
    COALESCE((order_payload->>'delivery_fee')::NUMERIC, 0),
    COALESCE((order_payload->>'discount')::NUMERIC, 0),
    (order_payload->>'total_amount')::NUMERIC,
    COALESCE((order_payload->>'total_cost')::NUMERIC, 0),
    COALESCE((order_payload->>'gross_profit')::NUMERIC, 0),
    COALESCE((order_payload->>'profit_margin_percent')::NUMERIC, 0),
    COALESCE(order_payload->>'payment_method', 'cod'),
    COALESCE(order_payload->>'payment_status', 'pending'),
    COALESCE(order_payload->>'order_status', 'pending'),
    order_payload->>'courier_name',
    order_payload->>'tracking_number',
    order_payload->>'admin_notes',
    order_payload->>'customer_notes',
    COALESCE((order_payload->>'is_custom_order')::BOOLEAN, false)
  )
  RETURNING id INTO v_order_id;

  -- 4. Insert Order Items
  FOR v_item IN SELECT * FROM jsonb_array_elements(items_payload) LOOP
    INSERT INTO public.order_items (
      order_id,
      product_id,
      product_name,
      product_sku,
      product_image,
      size,
      quantity,
      unit_price,
      cost_price,
      customization_fee,
      custom_name,
      custom_number,
      subtotal
    ) VALUES (
      v_order_id,
      (v_item->>'product_id')::UUID,
      v_item->>'product_name',
      v_item->>'product_sku',
      v_item->>'product_image',
      v_item->>'size',
      (v_item->>'quantity')::INTEGER,
      (v_item->>'unit_price')::NUMERIC,
      (v_item->>'cost_price')::NUMERIC,
      COALESCE((v_item->>'customization_fee')::NUMERIC, 0),
      v_item->>'player_name',
      v_item->>'player_number',
      (v_item->>'subtotal')::NUMERIC
    );
  END LOOP;

  RETURN jsonb_build_object(
    'success', true,
    'order_id', v_order_id,
    'order_number', v_order_number
  );
END;
$;

